// <auto-generated />
namespace PGMG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version22062020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version22062020));
        
        string IMigrationMetadata.Id
        {
            get { return "202006222355253_version22062020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
