// <auto-generated />
namespace PGMG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _241020202 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_241020202));
        
        string IMigrationMetadata.Id
        {
            get { return "202010241508210_24102020.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
