// <auto-generated />
namespace PGMG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _251020201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_251020201));
        
        string IMigrationMetadata.Id
        {
            get { return "202010251423324_25102020.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
