// <auto-generated />
namespace PGMG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version1512 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version1512));
        
        string IMigrationMetadata.Id
        {
            get { return "202005132303124_version15.1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
